System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "dependency-bundle.js": [
      "npm:whatwg-fetch@2.0.1.js",
      "npm:whatwg-fetch@2.0.1/fetch.js",
      "npm:react-leaflet@1.0.2.js",
      "npm:react-leaflet@1.0.2/lib/index.js",
      "npm:react-leaflet@1.0.2/lib/ZoomControl.js",
      "npm:react-leaflet@1.0.2/lib/types/controlPosition.js",
      "npm:react@15.4.1.js",
      "npm:react@15.4.1/react.js",
      "npm:react@15.4.1/lib/React.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.9.js",
      "npm:process@0.11.9/browser.js",
      "npm:react@15.4.1/lib/ReactElementValidator.js",
      "npm:fbjs@0.8.8/lib/warning.js",
      "npm:fbjs@0.8.8/lib/emptyFunction.js",
      "npm:react@15.4.1/lib/getIteratorFn.js",
      "npm:react@15.4.1/lib/canDefineProperty.js",
      "npm:react@15.4.1/lib/checkReactTypeSpec.js",
      "npm:react@15.4.1/lib/ReactComponentTreeHook.js",
      "npm:fbjs@0.8.8/lib/invariant.js",
      "npm:react@15.4.1/lib/ReactCurrentOwner.js",
      "npm:react@15.4.1/lib/reactProdInvariant.js",
      "npm:react@15.4.1/lib/ReactPropTypesSecret.js",
      "npm:react@15.4.1/lib/ReactPropTypeLocationNames.js",
      "npm:react@15.4.1/lib/ReactElement.js",
      "npm:react@15.4.1/lib/ReactElementSymbol.js",
      "npm:object-assign@4.1.0.js",
      "npm:object-assign@4.1.0/index.js",
      "npm:react@15.4.1/lib/onlyChild.js",
      "npm:react@15.4.1/lib/ReactVersion.js",
      "npm:react@15.4.1/lib/ReactPropTypes.js",
      "npm:react@15.4.1/lib/ReactDOMFactories.js",
      "npm:react@15.4.1/lib/ReactClass.js",
      "npm:fbjs@0.8.8/lib/emptyObject.js",
      "npm:react@15.4.1/lib/ReactNoopUpdateQueue.js",
      "npm:react@15.4.1/lib/ReactComponent.js",
      "npm:react@15.4.1/lib/ReactPureComponent.js",
      "npm:react@15.4.1/lib/ReactChildren.js",
      "npm:react@15.4.1/lib/traverseAllChildren.js",
      "npm:react@15.4.1/lib/KeyEscapeUtils.js",
      "npm:react@15.4.1/lib/PooledClass.js",
      "npm:react-leaflet@1.0.2/lib/MapControl.js",
      "npm:react-leaflet@1.0.2/lib/types/map.js",
      "npm:leaflet@1.0.2.js",
      "npm:leaflet@1.0.2/dist/leaflet-src.js",
      "npm:react-leaflet@1.0.2/lib/WMSTileLayer.js",
      "npm:react-leaflet@1.0.2/lib/GridLayer.js",
      "npm:react-leaflet@1.0.2/lib/MapLayer.js",
      "npm:react-leaflet@1.0.2/lib/MapComponent.js",
      "npm:lodash@4.17.3/clone.js",
      "npm:lodash@4.17.3/_baseClone.js",
      "npm:lodash@4.17.3/keys.js",
      "npm:lodash@4.17.3/isArrayLike.js",
      "npm:lodash@4.17.3/isLength.js",
      "npm:lodash@4.17.3/isFunction.js",
      "npm:lodash@4.17.3/isObject.js",
      "npm:lodash@4.17.3/_baseGetTag.js",
      "npm:lodash@4.17.3/_objectToString.js",
      "npm:lodash@4.17.3/_getRawTag.js",
      "npm:lodash@4.17.3/_Symbol.js",
      "npm:lodash@4.17.3/_root.js",
      "npm:lodash@4.17.3/_freeGlobal.js",
      "npm:lodash@4.17.3/_baseKeys.js",
      "npm:lodash@4.17.3/_nativeKeys.js",
      "npm:lodash@4.17.3/_overArg.js",
      "npm:lodash@4.17.3/_isPrototype.js",
      "npm:lodash@4.17.3/_arrayLikeKeys.js",
      "npm:lodash@4.17.3/isTypedArray.js",
      "npm:lodash@4.17.3/_nodeUtil.js",
      "npm:lodash@4.17.3/_baseUnary.js",
      "npm:lodash@4.17.3/_baseIsTypedArray.js",
      "npm:lodash@4.17.3/isObjectLike.js",
      "npm:lodash@4.17.3/_isIndex.js",
      "npm:lodash@4.17.3/isBuffer.js",
      "npm:lodash@4.17.3/stubFalse.js",
      "npm:lodash@4.17.3/isArray.js",
      "npm:lodash@4.17.3/isArguments.js",
      "npm:lodash@4.17.3/_baseIsArguments.js",
      "npm:lodash@4.17.3/_baseTimes.js",
      "npm:lodash@4.17.3/_initCloneObject.js",
      "npm:lodash@4.17.3/_getPrototype.js",
      "npm:lodash@4.17.3/_baseCreate.js",
      "npm:lodash@4.17.3/_initCloneByTag.js",
      "npm:lodash@4.17.3/_cloneTypedArray.js",
      "npm:lodash@4.17.3/_cloneArrayBuffer.js",
      "npm:lodash@4.17.3/_Uint8Array.js",
      "npm:lodash@4.17.3/_cloneSymbol.js",
      "npm:lodash@4.17.3/_cloneSet.js",
      "npm:lodash@4.17.3/_setToArray.js",
      "npm:lodash@4.17.3/_arrayReduce.js",
      "npm:lodash@4.17.3/_addSetEntry.js",
      "npm:lodash@4.17.3/_cloneRegExp.js",
      "npm:lodash@4.17.3/_cloneMap.js",
      "npm:lodash@4.17.3/_mapToArray.js",
      "npm:lodash@4.17.3/_addMapEntry.js",
      "npm:lodash@4.17.3/_cloneDataView.js",
      "npm:lodash@4.17.3/_initCloneArray.js",
      "npm:lodash@4.17.3/_getTag.js",
      "npm:lodash@4.17.3/_toSource.js",
      "npm:lodash@4.17.3/_WeakMap.js",
      "npm:lodash@4.17.3/_getNative.js",
      "npm:lodash@4.17.3/_getValue.js",
      "npm:lodash@4.17.3/_baseIsNative.js",
      "npm:lodash@4.17.3/_isMasked.js",
      "npm:lodash@4.17.3/_coreJsData.js",
      "npm:lodash@4.17.3/_Set.js",
      "npm:lodash@4.17.3/_Promise.js",
      "npm:lodash@4.17.3/_Map.js",
      "npm:lodash@4.17.3/_DataView.js",
      "npm:lodash@4.17.3/_getAllKeysIn.js",
      "npm:lodash@4.17.3/keysIn.js",
      "npm:lodash@4.17.3/_baseKeysIn.js",
      "npm:lodash@4.17.3/_nativeKeysIn.js",
      "npm:lodash@4.17.3/_getSymbolsIn.js",
      "npm:lodash@4.17.3/stubArray.js",
      "npm:lodash@4.17.3/_getSymbols.js",
      "npm:lodash@4.17.3/_arrayFilter.js",
      "npm:lodash@4.17.3/_arrayPush.js",
      "npm:lodash@4.17.3/_baseGetAllKeys.js",
      "npm:lodash@4.17.3/_getAllKeys.js",
      "npm:lodash@4.17.3/_copySymbolsIn.js",
      "npm:lodash@4.17.3/_copyObject.js",
      "npm:lodash@4.17.3/_baseAssignValue.js",
      "npm:lodash@4.17.3/_defineProperty.js",
      "npm:lodash@4.17.3/_assignValue.js",
      "npm:lodash@4.17.3/eq.js",
      "npm:lodash@4.17.3/_copySymbols.js",
      "npm:lodash@4.17.3/_copyArray.js",
      "npm:lodash@4.17.3/_cloneBuffer.js",
      "npm:lodash@4.17.3/_baseAssignIn.js",
      "npm:lodash@4.17.3/_baseAssign.js",
      "npm:lodash@4.17.3/_arrayEach.js",
      "npm:lodash@4.17.3/_Stack.js",
      "npm:lodash@4.17.3/_stackSet.js",
      "npm:lodash@4.17.3/_MapCache.js",
      "npm:lodash@4.17.3/_mapCacheSet.js",
      "npm:lodash@4.17.3/_getMapData.js",
      "npm:lodash@4.17.3/_isKeyable.js",
      "npm:lodash@4.17.3/_mapCacheHas.js",
      "npm:lodash@4.17.3/_mapCacheGet.js",
      "npm:lodash@4.17.3/_mapCacheDelete.js",
      "npm:lodash@4.17.3/_mapCacheClear.js",
      "npm:lodash@4.17.3/_ListCache.js",
      "npm:lodash@4.17.3/_listCacheSet.js",
      "npm:lodash@4.17.3/_assocIndexOf.js",
      "npm:lodash@4.17.3/_listCacheHas.js",
      "npm:lodash@4.17.3/_listCacheGet.js",
      "npm:lodash@4.17.3/_listCacheDelete.js",
      "npm:lodash@4.17.3/_listCacheClear.js",
      "npm:lodash@4.17.3/_Hash.js",
      "npm:lodash@4.17.3/_hashSet.js",
      "npm:lodash@4.17.3/_nativeCreate.js",
      "npm:lodash@4.17.3/_hashHas.js",
      "npm:lodash@4.17.3/_hashGet.js",
      "npm:lodash@4.17.3/_hashDelete.js",
      "npm:lodash@4.17.3/_hashClear.js",
      "npm:lodash@4.17.3/_stackHas.js",
      "npm:lodash@4.17.3/_stackGet.js",
      "npm:lodash@4.17.3/_stackDelete.js",
      "npm:lodash@4.17.3/_stackClear.js",
      "npm:lodash@4.17.3/forEach.js",
      "npm:lodash@4.17.3/_castFunction.js",
      "npm:lodash@4.17.3/identity.js",
      "npm:lodash@4.17.3/_baseEach.js",
      "npm:lodash@4.17.3/_createBaseEach.js",
      "npm:lodash@4.17.3/_baseForOwn.js",
      "npm:lodash@4.17.3/_baseFor.js",
      "npm:lodash@4.17.3/_createBaseFor.js",
      "npm:lodash@4.17.3/reduce.js",
      "npm:lodash@4.17.3/_baseReduce.js",
      "npm:lodash@4.17.3/_baseIteratee.js",
      "npm:lodash@4.17.3/property.js",
      "npm:lodash@4.17.3/_toKey.js",
      "npm:lodash@4.17.3/isSymbol.js",
      "npm:lodash@4.17.3/_isKey.js",
      "npm:lodash@4.17.3/_basePropertyDeep.js",
      "npm:lodash@4.17.3/_baseGet.js",
      "npm:lodash@4.17.3/_castPath.js",
      "npm:lodash@4.17.3/toString.js",
      "npm:lodash@4.17.3/_baseToString.js",
      "npm:lodash@4.17.3/_arrayMap.js",
      "npm:lodash@4.17.3/_stringToPath.js",
      "npm:lodash@4.17.3/_memoizeCapped.js",
      "npm:lodash@4.17.3/memoize.js",
      "npm:lodash@4.17.3/_baseProperty.js",
      "npm:lodash@4.17.3/_baseMatchesProperty.js",
      "npm:lodash@4.17.3/_matchesStrictComparable.js",
      "npm:lodash@4.17.3/_isStrictComparable.js",
      "npm:lodash@4.17.3/hasIn.js",
      "npm:lodash@4.17.3/_hasPath.js",
      "npm:lodash@4.17.3/_baseHasIn.js",
      "npm:lodash@4.17.3/get.js",
      "npm:lodash@4.17.3/_baseIsEqual.js",
      "npm:lodash@4.17.3/_baseIsEqualDeep.js",
      "npm:lodash@4.17.3/_equalObjects.js",
      "npm:lodash@4.17.3/_equalByTag.js",
      "npm:lodash@4.17.3/_equalArrays.js",
      "npm:lodash@4.17.3/_cacheHas.js",
      "npm:lodash@4.17.3/_arraySome.js",
      "npm:lodash@4.17.3/_SetCache.js",
      "npm:lodash@4.17.3/_setCacheHas.js",
      "npm:lodash@4.17.3/_setCacheAdd.js",
      "npm:lodash@4.17.3/_baseMatches.js",
      "npm:lodash@4.17.3/_getMatchData.js",
      "npm:lodash@4.17.3/_baseIsMatch.js",
      "npm:react-leaflet@1.0.2/lib/types/layerContainer.js",
      "npm:react-leaflet@1.0.2/lib/types/children.js",
      "npm:lodash@4.17.3/isEqual.js",
      "npm:react-leaflet@1.0.2/lib/Tooltip.js",
      "npm:react-dom@15.4.1.js",
      "npm:react-dom@15.4.1/index.js",
      "npm:react-dom@15.4.1/lib/ReactDOM.js",
      "npm:react-dom@15.4.1/lib/ReactDOMInvalidARIAHook.js",
      "npm:react-dom@15.4.1/lib/DOMProperty.js",
      "npm:react-dom@15.4.1/lib/reactProdInvariant.js",
      "npm:react-dom@15.4.1/lib/ReactDOMNullInputValuePropHook.js",
      "npm:react-dom@15.4.1/lib/ReactDOMUnknownPropertyHook.js",
      "npm:react-dom@15.4.1/lib/EventPluginRegistry.js",
      "npm:react-dom@15.4.1/lib/ReactInstrumentation.js",
      "npm:react-dom@15.4.1/lib/ReactDebugTool.js",
      "npm:fbjs@0.8.8/lib/performanceNow.js",
      "npm:fbjs@0.8.8/lib/performance.js",
      "npm:fbjs@0.8.8/lib/ExecutionEnvironment.js",
      "npm:react-dom@15.4.1/lib/ReactHostOperationHistoryHook.js",
      "npm:react-dom@15.4.1/lib/ReactInvalidSetStateWarningHook.js",
      "npm:react-dom@15.4.1/lib/renderSubtreeIntoContainer.js",
      "npm:react-dom@15.4.1/lib/ReactMount.js",
      "npm:react-dom@15.4.1/lib/shouldUpdateReactComponent.js",
      "npm:react-dom@15.4.1/lib/setInnerHTML.js",
      "npm:react-dom@15.4.1/lib/createMicrosoftUnsafeLocalFunction.js",
      "npm:react-dom@15.4.1/lib/DOMNamespaces.js",
      "npm:react-dom@15.4.1/lib/instantiateReactComponent.js",
      "npm:react-dom@15.4.1/lib/getNextDebugID.js",
      "npm:react-dom@15.4.1/lib/ReactHostComponent.js",
      "npm:react-dom@15.4.1/lib/ReactEmptyComponent.js",
      "npm:react-dom@15.4.1/lib/ReactCompositeComponent.js",
      "npm:fbjs@0.8.8/lib/shallowEqual.js",
      "npm:react-dom@15.4.1/lib/checkReactTypeSpec.js",
      "npm:react-dom@15.4.1/lib/ReactPropTypesSecret.js",
      "npm:react-dom@15.4.1/lib/ReactPropTypeLocationNames.js",
      "npm:react-dom@15.4.1/lib/ReactReconciler.js",
      "npm:react-dom@15.4.1/lib/ReactRef.js",
      "npm:react-dom@15.4.1/lib/ReactOwner.js",
      "npm:react-dom@15.4.1/lib/ReactNodeTypes.js",
      "npm:react-dom@15.4.1/lib/ReactInstanceMap.js",
      "npm:react-dom@15.4.1/lib/ReactErrorUtils.js",
      "npm:react-dom@15.4.1/lib/ReactComponentEnvironment.js",
      "npm:react-dom@15.4.1/lib/ReactUpdates.js",
      "npm:react-dom@15.4.1/lib/Transaction.js",
      "npm:react-dom@15.4.1/lib/ReactFeatureFlags.js",
      "npm:react-dom@15.4.1/lib/PooledClass.js",
      "npm:react-dom@15.4.1/lib/CallbackQueue.js",
      "npm:react-dom@15.4.1/lib/ReactUpdateQueue.js",
      "npm:react-dom@15.4.1/lib/ReactMarkupChecksum.js",
      "npm:react-dom@15.4.1/lib/adler32.js",
      "npm:react-dom@15.4.1/lib/ReactDOMFeatureFlags.js",
      "npm:react-dom@15.4.1/lib/ReactDOMContainerInfo.js",
      "npm:react-dom@15.4.1/lib/validateDOMNesting.js",
      "npm:react-dom@15.4.1/lib/ReactDOMComponentTree.js",
      "npm:react-dom@15.4.1/lib/ReactDOMComponentFlags.js",
      "npm:react-dom@15.4.1/lib/ReactBrowserEventEmitter.js",
      "npm:react-dom@15.4.1/lib/isEventSupported.js",
      "npm:react-dom@15.4.1/lib/getVendorPrefixedEventName.js",
      "npm:react-dom@15.4.1/lib/ViewportMetrics.js",
      "npm:react-dom@15.4.1/lib/ReactEventEmitterMixin.js",
      "npm:react-dom@15.4.1/lib/EventPluginHub.js",
      "npm:react-dom@15.4.1/lib/forEachAccumulated.js",
      "npm:react-dom@15.4.1/lib/accumulateInto.js",
      "npm:react-dom@15.4.1/lib/EventPluginUtils.js",
      "npm:react-dom@15.4.1/lib/DOMLazyTree.js",
      "npm:react-dom@15.4.1/lib/setTextContent.js",
      "npm:react-dom@15.4.1/lib/escapeTextContentForBrowser.js",
      "npm:react-dom@15.4.1/lib/getHostComponentFromComposite.js",
      "npm:react-dom@15.4.1/lib/findDOMNode.js",
      "npm:react-dom@15.4.1/lib/ReactVersion.js",
      "npm:react-dom@15.4.1/lib/ReactDefaultInjection.js",
      "npm:react-dom@15.4.1/lib/SimpleEventPlugin.js",
      "npm:react-dom@15.4.1/lib/getEventCharCode.js",
      "npm:react-dom@15.4.1/lib/SyntheticWheelEvent.js",
      "npm:react-dom@15.4.1/lib/SyntheticMouseEvent.js",
      "npm:react-dom@15.4.1/lib/getEventModifierState.js",
      "npm:react-dom@15.4.1/lib/SyntheticUIEvent.js",
      "npm:react-dom@15.4.1/lib/getEventTarget.js",
      "npm:react-dom@15.4.1/lib/SyntheticEvent.js",
      "npm:react-dom@15.4.1/lib/SyntheticTransitionEvent.js",
      "npm:react-dom@15.4.1/lib/SyntheticTouchEvent.js",
      "npm:react-dom@15.4.1/lib/SyntheticDragEvent.js",
      "npm:react-dom@15.4.1/lib/SyntheticKeyboardEvent.js",
      "npm:react-dom@15.4.1/lib/getEventKey.js",
      "npm:react-dom@15.4.1/lib/SyntheticFocusEvent.js",
      "npm:react-dom@15.4.1/lib/SyntheticClipboardEvent.js",
      "npm:react-dom@15.4.1/lib/SyntheticAnimationEvent.js",
      "npm:react-dom@15.4.1/lib/EventPropagators.js",
      "npm:fbjs@0.8.8/lib/EventListener.js",
      "npm:react-dom@15.4.1/lib/SelectEventPlugin.js",
      "npm:react-dom@15.4.1/lib/isTextInputElement.js",
      "npm:fbjs@0.8.8/lib/getActiveElement.js",
      "npm:react-dom@15.4.1/lib/ReactInputSelection.js",
      "npm:fbjs@0.8.8/lib/focusNode.js",
      "npm:fbjs@0.8.8/lib/containsNode.js",
      "npm:fbjs@0.8.8/lib/isTextNode.js",
      "npm:fbjs@0.8.8/lib/isNode.js",
      "npm:react-dom@15.4.1/lib/ReactDOMSelection.js",
      "npm:react-dom@15.4.1/lib/getTextContentAccessor.js",
      "npm:react-dom@15.4.1/lib/getNodeForCharacterOffset.js",
      "npm:react-dom@15.4.1/lib/SVGDOMPropertyConfig.js",
      "npm:react-dom@15.4.1/lib/ReactReconcileTransaction.js",
      "npm:react-dom@15.4.1/lib/ReactInjection.js",
      "npm:react-dom@15.4.1/lib/ReactEventListener.js",
      "npm:fbjs@0.8.8/lib/getUnboundedScrollPosition.js",
      "npm:react-dom@15.4.1/lib/ReactDefaultBatchingStrategy.js",
      "npm:react-dom@15.4.1/lib/ReactDOMTextComponent.js",
      "npm:react-dom@15.4.1/lib/DOMChildrenOperations.js",
      "npm:react-dom@15.4.1/lib/Danger.js",
      "npm:fbjs@0.8.8/lib/createNodesFromMarkup.js",
      "npm:fbjs@0.8.8/lib/getMarkupWrap.js",
      "npm:fbjs@0.8.8/lib/createArrayFromMixed.js",
      "npm:react-dom@15.4.1/lib/ReactDOMTreeTraversal.js",
      "npm:react-dom@15.4.1/lib/ReactDOMEmptyComponent.js",
      "npm:react-dom@15.4.1/lib/ReactDOMComponent.js",
      "npm:react-dom@15.4.1/lib/ReactServerRenderingTransaction.js",
      "npm:react-dom@15.4.1/lib/ReactServerUpdateQueue.js",
      "npm:react-dom@15.4.1/lib/ReactMultiChild.js",
      "npm:react-dom@15.4.1/lib/flattenChildren.js",
      "npm:react-dom@15.4.1/lib/traverseAllChildren.js",
      "npm:react-dom@15.4.1/lib/KeyEscapeUtils.js",
      "npm:react-dom@15.4.1/lib/getIteratorFn.js",
      "npm:react-dom@15.4.1/lib/ReactElementSymbol.js",
      "npm:react-dom@15.4.1/lib/ReactChildReconciler.js",
      "npm:react-dom@15.4.1/lib/ReactDOMTextarea.js",
      "npm:react-dom@15.4.1/lib/LinkedValueUtils.js",
      "npm:react-dom@15.4.1/lib/ReactDOMSelect.js",
      "npm:react-dom@15.4.1/lib/ReactDOMOption.js",
      "npm:react-dom@15.4.1/lib/ReactDOMInput.js",
      "npm:react-dom@15.4.1/lib/DOMPropertyOperations.js",
      "npm:react-dom@15.4.1/lib/quoteAttributeValueForBrowser.js",
      "npm:react-dom@15.4.1/lib/CSSPropertyOperations.js",
      "npm:fbjs@0.8.8/lib/memoizeStringOnly.js",
      "npm:fbjs@0.8.8/lib/hyphenateStyleName.js",
      "npm:fbjs@0.8.8/lib/hyphenate.js",
      "npm:react-dom@15.4.1/lib/dangerousStyleValue.js",
      "npm:react-dom@15.4.1/lib/CSSProperty.js",
      "npm:fbjs@0.8.8/lib/camelizeStyleName.js",
      "npm:fbjs@0.8.8/lib/camelize.js",
      "npm:react-dom@15.4.1/lib/AutoFocusUtils.js",
      "npm:react-dom@15.4.1/lib/ReactComponentBrowserEnvironment.js",
      "npm:react-dom@15.4.1/lib/ReactDOMIDOperations.js",
      "npm:react-dom@15.4.1/lib/HTMLDOMPropertyConfig.js",
      "npm:react-dom@15.4.1/lib/EnterLeaveEventPlugin.js",
      "npm:react-dom@15.4.1/lib/DefaultEventPluginOrder.js",
      "npm:react-dom@15.4.1/lib/ChangeEventPlugin.js",
      "npm:react-dom@15.4.1/lib/BeforeInputEventPlugin.js",
      "npm:react-dom@15.4.1/lib/SyntheticInputEvent.js",
      "npm:react-dom@15.4.1/lib/SyntheticCompositionEvent.js",
      "npm:react-dom@15.4.1/lib/FallbackCompositionState.js",
      "npm:react-dom@15.4.1/lib/ARIADOMPropertyConfig.js",
      "npm:react-leaflet@1.0.2/lib/TileLayer.js",
      "npm:react-leaflet@1.0.2/lib/ScaleControl.js",
      "npm:react-leaflet@1.0.2/lib/Rectangle.js",
      "npm:react-leaflet@1.0.2/lib/Path.js",
      "npm:lodash@4.17.3/pick.js",
      "npm:lodash@4.17.3/_flatRest.js",
      "npm:lodash@4.17.3/_setToString.js",
      "npm:lodash@4.17.3/_shortOut.js",
      "npm:lodash@4.17.3/_baseSetToString.js",
      "npm:lodash@4.17.3/constant.js",
      "npm:lodash@4.17.3/_overRest.js",
      "npm:lodash@4.17.3/_apply.js",
      "npm:lodash@4.17.3/flatten.js",
      "npm:lodash@4.17.3/_baseFlatten.js",
      "npm:lodash@4.17.3/_isFlattenable.js",
      "npm:lodash@4.17.3/_basePick.js",
      "npm:lodash@4.17.3/_basePickBy.js",
      "npm:lodash@4.17.3/_baseSet.js",
      "npm:react-leaflet@1.0.2/lib/types/bounds.js",
      "npm:react-leaflet@1.0.2/lib/types/latlngList.js",
      "npm:react-leaflet@1.0.2/lib/types/latlng.js",
      "npm:react-leaflet@1.0.2/lib/Popup.js",
      "npm:react-leaflet@1.0.2/lib/Polyline.js",
      "npm:react-leaflet@1.0.2/lib/Polygon.js",
      "npm:react-leaflet@1.0.2/lib/Pane.js",
      "npm:warning@3.0.0.js",
      "npm:warning@3.0.0/browser.js",
      "npm:lodash@4.17.3/omit.js",
      "npm:lodash@4.17.3/_customOmitClone.js",
      "npm:lodash@4.17.3/isPlainObject.js",
      "npm:lodash@4.17.3/_baseUnset.js",
      "npm:lodash@4.17.3/_parent.js",
      "npm:lodash@4.17.3/_baseSlice.js",
      "npm:lodash@4.17.3/last.js",
      "npm:lodash@4.17.3/uniqueId.js",
      "npm:react-leaflet@1.0.2/lib/Marker.js",
      "npm:react-leaflet@1.0.2/lib/Map.js",
      "npm:lodash@4.17.3/isUndefined.js",
      "npm:react-leaflet@1.0.2/lib/LayersControl.js",
      "npm:react-leaflet@1.0.2/lib/LayerGroup.js",
      "npm:react-leaflet@1.0.2/lib/ImageOverlay.js",
      "npm:react-leaflet@1.0.2/lib/GeoJSON.js",
      "npm:react-leaflet@1.0.2/lib/FeatureGroup.js",
      "npm:react-leaflet@1.0.2/lib/CircleMarker.js",
      "npm:react-leaflet@1.0.2/lib/Circle.js",
      "npm:react-leaflet@1.0.2/lib/AttributionControl.js",
      "npm:react-leaflet@1.0.2/lib/types/index.js",
      "npm:babel-runtime@5.8.38/helpers/inherits.js",
      "npm:babel-runtime@5.8.38/core-js/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/$.core.js",
      "npm:core-js@1.2.7/library/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/$.set-proto.js",
      "npm:core-js@1.2.7/library/modules/$.ctx.js",
      "npm:core-js@1.2.7/library/modules/$.a-function.js",
      "npm:core-js@1.2.7/library/modules/$.an-object.js",
      "npm:core-js@1.2.7/library/modules/$.is-object.js",
      "npm:core-js@1.2.7/library/modules/$.js",
      "npm:core-js@1.2.7/library/modules/$.export.js",
      "npm:core-js@1.2.7/library/modules/$.global.js",
      "npm:babel-runtime@5.8.38/core-js/object/create.js",
      "npm:core-js@1.2.7/library/fn/object/create.js",
      "npm:babel-runtime@5.8.38/helpers/get.js",
      "npm:babel-runtime@5.8.38/core-js/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/$.object-sap.js",
      "npm:core-js@1.2.7/library/modules/$.fails.js",
      "npm:core-js@1.2.7/library/modules/$.to-iobject.js",
      "npm:core-js@1.2.7/library/modules/$.defined.js",
      "npm:core-js@1.2.7/library/modules/$.iobject.js",
      "npm:core-js@1.2.7/library/modules/$.cof.js",
      "npm:babel-runtime@5.8.38/helpers/create-class.js",
      "npm:babel-runtime@5.8.38/core-js/object/define-property.js",
      "npm:core-js@1.2.7/library/fn/object/define-property.js",
      "npm:babel-runtime@5.8.38/helpers/class-call-check.js",
      "github:Leaflet/Leaflet@1.0.2.js",
      "github:Leaflet/Leaflet@1.0.2/dist/leaflet-src.js"
    ]
  },

  map: {
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "core-js": "npm:core-js@1.2.7",
    "fetch": "npm:whatwg-fetch@2.0.1",
    "leaflet": "github:Leaflet/Leaflet@1.0.2",
    "react": "npm:react@15.4.1",
    "react-dom": "npm:react-dom@15.4.1",
    "react-leaflet": "npm:react-leaflet@1.0.2",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-domain@0.1.0": {
      "domain-browser": "npm:domain-browser@1.1.7"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.9"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:jspm/nodelibs-zlib@0.1.0": {
      "browserify-zlib": "npm:browserify-zlib@0.1.4"
    },
    "npm:asap@2.0.5": {
      "domain": "github:jspm/nodelibs-domain@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:browserify-zlib@0.1.4": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "pako": "npm:pako@0.2.9",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readable-stream": "npm:readable-stream@2.2.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:buffer-shims@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.8",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:domain-browser@1.1.7": {
      "events": "github:jspm/nodelibs-events@0.1.1"
    },
    "npm:encoding@0.1.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "iconv-lite": "npm:iconv-lite@0.4.15"
    },
    "npm:fbjs@0.8.8": {
      "core-js": "npm:core-js@1.2.7",
      "isomorphic-fetch": "npm:isomorphic-fetch@2.2.1",
      "loose-envify": "npm:loose-envify@1.3.0",
      "object-assign": "npm:object-assign@4.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "promise": "npm:promise@7.1.1",
      "setimmediate": "npm:setimmediate@1.0.5",
      "ua-parser-js": "npm:ua-parser-js@0.7.12"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:iconv-lite@0.4.15": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:isomorphic-fetch@2.2.1": {
      "node-fetch": "npm:node-fetch@1.6.3",
      "whatwg-fetch": "npm:whatwg-fetch@2.0.1"
    },
    "npm:loose-envify@1.3.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "js-tokens": "npm:js-tokens@2.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:node-fetch@1.6.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "encoding": "npm:encoding@0.1.12",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "is-stream": "npm:is-stream@1.1.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "zlib": "github:jspm/nodelibs-zlib@0.1.0"
    },
    "npm:pako@0.2.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process-nextick-args@1.0.7": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.9": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:promise@7.1.1": {
      "asap": "npm:asap@2.0.5",
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:react-dom@15.4.1": {
      "fbjs": "npm:fbjs@0.8.8",
      "loose-envify": "npm:loose-envify@1.3.0",
      "object-assign": "npm:object-assign@4.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.4.1"
    },
    "npm:react-leaflet@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "leaflet": "npm:leaflet@1.0.2",
      "lodash": "npm:lodash@4.17.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.4.1",
      "react-dom": "npm:react-dom@15.4.1",
      "warning": "npm:warning@3.0.0"
    },
    "npm:react@15.4.1": {
      "fbjs": "npm:fbjs@0.8.8",
      "loose-envify": "npm:loose-envify@1.3.0",
      "object-assign": "npm:object-assign@4.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:readable-stream@2.2.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-shims": "npm:buffer-shims@1.0.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "process-nextick-args": "npm:process-nextick-args@1.0.7",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util-deprecate": "npm:util-deprecate@1.0.2"
    },
    "npm:setimmediate@1.0.5": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:ua-parser-js@0.7.12": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util-deprecate@1.0.2": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:warning@3.0.0": {
      "loose-envify": "npm:loose-envify@1.3.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
